In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
a.ndim

1

In [ ]:
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.ndim

2

In [ ]:
type(b)

numpy.ndarray

create with tuple

In [ ]:
c =np.array((1,2,3))

In [ ]:
print(c)

[1 2 3]


In [ ]:
c.ndim

1

In [ ]:
z = np.zeros(4)

In [ ]:
print(z)

[0. 0. 0. 0.]


In [ ]:
z = np.zeros((2,2))

In [ ]:
print(z)

[[0. 0.]
 [0. 0.]]


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a = np.empty(5)

In [ ]:
print(a)

[0.   0.25 0.5  0.75 1.  ]


arange()

In [ ]:
c = np.arange(0,11)

In [ ]:
type(c)

numpy.ndarray

In [ ]:
 b = range(0,11)

In [ ]:
type(b)

range

In [ ]:
for i in range(0,11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
z = np.arange(2,11,2)

In [ ]:
for i in z:
  print(i)

2
4
6
8
10


In [ ]:
np.linspace(1,6,num=6)

array([1., 2., 3., 4., 5., 6.])

In [ ]:
a = np.array([9,1,3,4,6,8])

In [ ]:
a.ndim

1

In [ ]:
a

array([9, 1, 3, 4, 6, 8])

In [ ]:
np.reshape(a, newshape=(3,2))

array([[9, 1],
       [3, 4],
       [6, 8]])

#Attributes

In [ ]:
a = np.array([[9,1,3],[5,4,8]])
a

array([[9, 1, 3],
       [5, 4, 8]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

#sort



In [ ]:
a = np.array([8,6,7,5,7,3,0,-2])

In [ ]:
np.sort(a)

array([-2,  0,  3,  5,  6,  7,  7,  8])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((b,a))

In [ ]:
c

array([4, 5, 6, 1, 2, 3])

In [ ]:
a = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [ ]:
a

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
b = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [ ]:
b

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
c = np.concatenate((a,b), axis = 1)

In [ ]:
c

array([[ 1,  2,  3,  1,  2,  3],
       [ 5,  6,  7,  5,  6,  7],
       [ 8,  9, 10,  8,  9, 10]])

#slicing

In [ ]:
a = np.array([8,6,7,5,7,3,0,-2])

In [ ]:
a[-5]

5

In [ ]:
a[2:]

array([ 7,  5,  7,  3,  0, -2])

In [ ]:
a[:4]

array([8, 6, 7, 5])

#Transpose

In [ ]:
b = np.array([[1,-2,3],[5,6,7],[8,9,10]])

In [ ]:
b

array([[ 1, -2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
b.transpose()

array([[ 1,  5,  8],
       [-2,  6,  9],
       [ 3,  7, 10]])

# min  max sum

In [ ]:
b.min()

-2

In [ ]:
b.max()

10

In [ ]:
b.sum()

47

#random seed

In [ ]:
from numpy import random

In [ ]:
random.seed(0)
x = random.randint(40, size=(10))
print(x)

[ 0  3  3 39  9 19 21 36 23  6]


In [ ]:
random.seed(70)
x = random.randint(40, size=(10))
print(x)

[14 22 24  0 21 20 39  8 32 23]


In [ ]:
random.seed(70)
x = random.randint(40, size=(10))
print(x)

[14 22 24  0 21 20 39  8 32 23]
